### ISSUE TITLE
Pipeline will not run due to caching

### ISSUE THREAD

**Issue by kstawiski** [mdelcorvo/TOSCA#1]
Hi,
Thanks for providing the pipeline. I'm trying to test it on my samples.

The first problem I have is this error:
```
WorkflowError in line 64 of rules/genome.smk:
Rule is marked for between workflow caching but has multiple output files. This is only allowed if multiext() is used to declare them (see docs on between workflow caching).
  File "Snakefile", line 28, in <module>
  File "rules/genome.smk", line 64, in <module>
```

I removed caching from the rules for now.

**Comment by infobiomatics** [comment]
Hi, 
I have got the same problem. 
@kstawiski Did you set the cache to False in the rule files?
Thanks,
Christian

**Comment by ibrahimkurt** [comment]
Hi @infobiomatics,

I had the same error and set the cache to False in the rule files. Seemed to bypass the issue.
